--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: feedback; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.feedback (id, user_id, raw_feedback, ai_summary, priority, feedback_type, device_info, app_version, created_at, processed_at, status, tags, metadata) FROM stdin;
96bd390a-f59b-4ed8-96ba-cd32cad5ffc0	f416eb32-ce7d-4074-a02c-5ce98b679320	This app is absolutely fantastic. Honestly, it's just going to change so many people's lives. It's going to be truly incredible. So, well done.	User feedback: This app is absolutely fantastic. Honestly, it's just going to change so many people's lives. It's g...	medium	general	{"version": "18.5", "platform": "ios", "timestamp": "2025-07-29T12:40:40.647Z", "appVersion": "1.0.0", "buildNumber": "1"}	1.0.0	2025-07-29 12:40:40.943398+00	\N	pending	{feedback,user_input}	{"impact": "medium", "urgency": "later", "sentiment": "neutral"}
e46b04af-3442-4ee0-a0c7-e4193214d405	f416eb32-ce7d-4074-a02c-5ce98b679320	What I think would be absolutely wonderful is if you could create on registration a wizard that goes through each of the steps to collect that memory information that's going to be so important for the initial sessions. To build up the memory over time is a bit more challenging.	User feedback: What I think would be absolutely wonderful is if you could create on registration a wizard that goes...	medium	general	{"version": "18.5", "platform": "ios", "timestamp": "2025-07-30T07:28:52.567Z", "appVersion": "1.0.0", "buildNumber": "1"}	1.0.0	2025-07-30 07:28:52.777287+00	\N	pending	{feedback,user_input}	{"impact": "medium", "urgency": "later", "sentiment": "neutral"}
c81abdaf-3dcd-46a9-9d26-67049e995ba6	f416eb32-ce7d-4074-a02c-5ce98b679320	I think you need to get a psychologist or psychiatrist on the system to analyze outputs. Could it be done with AI, I wonder. Like, to help him see... Yeah, certain conversations. Maybe it's something like, after a conversation session is finished, you can, like, rate it. Maybe something like that.	The user suggests incorporating professional mental health expertise into the system, possibly through AI, to analyze conversation outputs. They also propose a feature to rate conversation sessions after completion.	medium	feature_request	{"version": "18.5", "platform": "ios", "timestamp": "2025-07-30T07:56:45.614Z", "appVersion": "1.0.0", "buildNumber": "1"}	1.0.0	2025-07-30 07:56:51.403838+00	\N	pending	{"AI analysis","professional input","session rating"}	{"impact": "medium", "urgency": "later", "userType": "new", "sentiment": "neutral", "therapeuticRelevance": "high"}
c3f39d84-c10a-4dc5-84f9-f08bfa9d80ad	f416eb32-ce7d-4074-a02c-5ce98b679320	I like the idea of having a relationship open session where the user just enables the mic and then two people have a discussion so they talk about what's going on for them so I'm triggered in this and I'm feeling sad because you didn't make me a cup of tea this morning and I don't feel like you ever listen to me and da da da and each person talks and the AI can pick up by the tone and the sound of the two different voices who is who in the situation and then maybe give help and context and guidance and pattern recognition conflict resolution staff to a discussion sort of be a impartial third party that can listen in and then it's in a session and you can click a button to to enable that and then all those those session like message bubbles will appear from each person and then the AI will give a response I'd have to think about the design a bit more but something like that would be cool	The user suggests a new feature where two people can have a discussion with the AI listening in, recognizing voice patterns, and providing help, context, guidance, and conflict resolution. The user envisions this as an open session that can be enabled with a button, with the AI providing responses in message bubbles.	medium	feature_request	{"version": "18.5", "platform": "ios", "timestamp": "2025-07-30T08:04:48.911Z", "appVersion": "1.0.0", "buildNumber": "1"}	1.0.0	2025-07-30 08:04:57.985681+00	\N	pending	{"AI-powered conversation","voice recognition","conflict resolution","new feature","relationship session"}	{"impact": "medium", "urgency": "later", "userType": "returning", "sentiment": "positive", "therapeuticRelevance": "high"}
aa7f06db-0696-42e5-bd36-02ae199775f5	7b2233b3-97d5-4250-9587-0299f5157884	I think the AI needs to respond quicker.	The user suggests that the AI response time should be improved.	medium	performance	{"version": "18.5", "platform": "ios", "timestamp": "2025-07-30T20:22:34.778Z", "appVersion": "1.0.0", "buildNumber": "1"}	1.0.0	2025-07-30 20:22:41.351573+00	\N	pending	{"AI response",speed,performance}	{"impact": "medium", "urgency": "soon", "userType": "unknown", "sentiment": "neutral", "therapeuticRelevance": "high"}
c1c1336a-7ca3-4787-a1ae-7c1e93d03b4c	f416eb32-ce7d-4074-a02c-5ce98b679320	It would be really cool to have a function where the user can have sort of a sliding scale of how much pushback they want or how much, like, do they just want to be heard and it to all be agreeable, or do they want to be challenged and there to be growth?	The user suggests a new feature for a sliding scale to control the level of challenge or agreement in the app's responses, allowing for customization of their therapeutic experience.	medium	feature_request	{"version": "18.5", "platform": "ios", "timestamp": "2025-08-01T18:08:39.581Z", "appVersion": "1.0.0", "buildNumber": "2"}	1.0.0	2025-08-01 18:08:46.130624+00	\N	pending	{customization,user_experience,therapeutic_interaction}	{"impact": "medium", "urgency": "later", "userType": "returning", "sentiment": "positive", "therapeuticRelevance": "high"}
5314c185-8417-47f5-910c-f931d4d591c7	f416eb32-ce7d-4074-a02c-5ce98b679320	The login needs to be a lot more seamless so you shouldn't have to put in your username and password every time you open the app. Maybe like a face ID or like a quick quick login feature would be would be good. can it remeber your session on the android or apple?	The user suggests improvements for the login process, requesting a more seamless experience such as face ID or quick login feature. They also ask about session memory on Android and Apple devices.	high	feature_request	{"version": "18.5", "platform": "ios", "timestamp": "2025-08-02T12:35:09.965Z", "appVersion": "1.0.0", "buildNumber": "2"}	1.0.0	2025-08-02 12:35:15.585099+00	\N	pending	{login,user_experience,session_memory,face_ID,quick_login}	{"impact": "medium", "urgency": "soon", "userType": "returning", "sentiment": "neutral", "therapeuticRelevance": "low"}
2441da29-12c8-476a-914b-984ab730334b	f416eb32-ce7d-4074-a02c-5ce98b679320	I had an idea for the powder paint, or actually no, for the logo, that all the lunar colors had sort of the powder paint vibrancy and something creative and abstract but with all the lunar colors.	The user suggests a design change for the logo, proposing that it incorporates the vibrancy of powder paint and the lunar colors in an abstract, creative manner.	low	ui_ux	{"version": "18.5", "platform": "ios", "timestamp": "2025-08-02T12:35:52.876Z", "appVersion": "1.0.0", "buildNumber": "2"}	1.0.0	2025-08-02 12:35:59.395045+00	\N	pending	{logo_design,color_scheme,creativity,abstract}	{"impact": "low", "urgency": "later", "userType": "returning", "sentiment": "positive", "therapeuticRelevance": "low"}
6c5d22ae-4d8f-4c95-934b-01070cbcbac2	f416eb32-ce7d-4074-a02c-5ce98b679320	so the previous feedback was actually not for the logo but for the splash screen the logo should be white on that sort of powder paint abstract color pop, so it should be the splash screen	The user suggests that the logo on the splash screen should be white against the abstract color pop background.	low	ui_ux	{"version": "18.5", "platform": "ios", "timestamp": "2025-08-02T12:37:31.236Z", "appVersion": "1.0.0", "buildNumber": "2"}	1.0.0	2025-08-02 12:37:35.22116+00	\N	pending	{splash_screen,logo_color,design_suggestion}	{"impact": "low", "urgency": "later", "userType": "returning", "sentiment": "neutral", "therapeuticRelevance": "low"}
8aaf66fd-b0eb-48c6-aa74-4c644799ec7d	f416eb32-ce7d-4074-a02c-5ce98b679320	Thinking about having psychological text and textbooks and resources that are part of the vector database that can be specifically accessed for this. Where the vector database comes into play, it looks at the question and it references the database as well, and just thinking, is there a way to contextualize, like, this is about the user and this is the professional landscape and this is what it looks like. So EFT, CBT, all these different, IFS, all these different therapeutic landscapes to have it in this vector database that can be accessed.	The user suggests incorporating psychological texts, textbooks, and resources into the app's vector database for reference. They also propose a way to contextualize the information based on the user and various therapeutic landscapes like EFT, CBT, and IFS.	medium	feature_request	{"version": "18.5", "platform": "ios", "timestamp": "2025-08-03T10:04:37.547Z", "appVersion": "1.0.0", "buildNumber": "2"}	1.0.0	2025-08-03 10:04:43.707154+00	\N	pending	{"vector database","therapeutic resources",contextualization,CBT,EFT,IFS}	{"impact": "medium", "urgency": "later", "userType": "power", "sentiment": "neutral", "therapeuticRelevance": "high"}
a2ad6c4f-1059-46e1-8013-1d15ec3c13b1	f416eb32-ce7d-4074-a02c-5ce98b679320	So, for the text-based interactions with OpenAI, it's best to use API, not WebSockets, currently using WebSockets, but only use WebSockets when it's an open voice dialogue straight to OpenAI. So, the voice goes to the server and acts as a proxy server and goes straight to OpenAI. That's the only time to use WebSockets. Otherwise, you can use chunking with the AI to give that perceived speed as being much faster.	The user suggests using API for text-based interactions with OpenAI instead of WebSockets, reserving the latter for open voice dialogues. They also recommend using chunking with the AI for perceived speed improvement.	medium	feature_request	{"version": "18.5", "platform": "ios", "timestamp": "2025-08-03T14:28:12.148Z", "appVersion": "1.0.0", "buildNumber": "2"}	1.0.0	2025-08-03 14:28:17.666129+00	\N	pending	{API,WebSockets,OpenAI,speed,voice_dialogue}	{"impact": "medium", "urgency": "soon", "userType": "power", "sentiment": "neutral", "therapeuticRelevance": "low"}
\.


--
-- PostgreSQL database dump complete
--

